//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fakeSMTP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fakeSMTP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 220 {0} MailRecv 0.1.2-b4; {1}.
        /// </summary>
        internal static string MSG_220_Banner {
            get {
                return ResourceManager.GetString("MSG_220_Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 221 Closing connection..
        /// </summary>
        internal static string MSG_221_ClosingConnection {
            get {
                return ResourceManager.GetString("MSG_221_ClosingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 Hello {0} ([{1}]), nice to meet you..
        /// </summary>
        internal static string MSG_250_1 {
            get {
                return ResourceManager.GetString("MSG_250_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 Hello {0} ([{1}]), nice to meet you.
        ///250-HELP
        ///250-VRFY
        ///250-EXPN
        ///250 NOOP.
        /// </summary>
        internal static string MSG_250_2 {
            get {
                return ResourceManager.GetString("MSG_250_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 ({0}) OK.
        /// </summary>
        internal static string MSG_250_OK {
            get {
                return ResourceManager.GetString("MSG_250_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 OK.
        /// </summary>
        internal static string MSG_250_OK2 {
            get {
                return ResourceManager.GetString("MSG_250_OK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 {0} OK.
        /// </summary>
        internal static string MSG_250_OK3 {
            get {
                return ResourceManager.GetString("MSG_250_OK3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 {0}... Recipient ok.
        /// </summary>
        internal static string MSG_250_RecipientOk {
            get {
                return ResourceManager.GetString("MSG_250_RecipientOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 Reset Ok.
        /// </summary>
        internal static string MSG_250_ResetOk {
            get {
                return ResourceManager.GetString("MSG_250_ResetOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250 {0}... Sender ok.
        /// </summary>
        internal static string MSG_250_SenderOk {
            get {
                return ResourceManager.GetString("MSG_250_SenderOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 252 Cannot VRFY user; try RCPT to attempt delivery (or try finger).
        /// </summary>
        internal static string MSG_252_CannotVrfy {
            get {
                return ResourceManager.GetString("MSG_252_CannotVrfy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 354 Start mail input; end with &lt;CRLF&gt;.&lt;CRLF&gt;.
        /// </summary>
        internal static string MSG_354_StartMailInput {
            get {
                return ResourceManager.GetString("MSG_354_StartMailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 421 Service temporarily unavailable, closing transmission channel..
        /// </summary>
        internal static string MSG_421_ServiceTemporarilyUnavailable {
            get {
                return ResourceManager.GetString("MSG_421_ServiceTemporarilyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 422 Recipient mailbox exceeded quota limit..
        /// </summary>
        internal static string MSG_422_MailboxExceededQuota {
            get {
                return ResourceManager.GetString("MSG_422_MailboxExceededQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 442 Connection timed out..
        /// </summary>
        internal static string MSG_442_ConnectionTimedOut {
            get {
                return ResourceManager.GetString("MSG_442_ConnectionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 451 Max NOOP count exceeded.
        /// </summary>
        internal static string MSG_451_MaxNoop {
            get {
                return ResourceManager.GetString("MSG_451_MaxNoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 451 Max recipient verification exceeded.
        /// </summary>
        internal static string MSG_451_MaxRecipients {
            get {
                return ResourceManager.GetString("MSG_451_MaxRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 451 Session messages count exceeded.
        /// </summary>
        internal static string MSG_451_SessionMessagesCountExceeded {
            get {
                return ResourceManager.GetString("MSG_451_SessionMessagesCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 452 Too many recipients.
        /// </summary>
        internal static string MSG_452_TooManyRecipients {
            get {
                return ResourceManager.GetString("MSG_452_TooManyRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 471 Bad or missing RCPT command.
        /// </summary>
        internal static string MSG_471_BadOrMissingRcpt {
            get {
                return ResourceManager.GetString("MSG_471_BadOrMissingRcpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Command unrecognized.
        /// </summary>
        internal static string MSG_500_CommandUnrecognized1 {
            get {
                return ResourceManager.GetString("MSG_500_CommandUnrecognized1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 Command unrecognized ({0}).
        /// </summary>
        internal static string MSG_500_CommandUnrecognized2 {
            get {
                return ResourceManager.GetString("MSG_500_CommandUnrecognized2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501 Invalid {0}.
        /// </summary>
        internal static string MSG_501_Invalid {
            get {
                return ResourceManager.GetString("MSG_501_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501 {0} needs argument.
        /// </summary>
        internal static string MSG_501_NeedsArgument {
            get {
                return ResourceManager.GetString("MSG_501_NeedsArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501 spoofed {0}.
        /// </summary>
        internal static string MSG_501_Spoofed {
            get {
                return ResourceManager.GetString("MSG_501_Spoofed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503 you already sent {0} ....
        /// </summary>
        internal static string MSG_503_AlreadySent {
            get {
                return ResourceManager.GetString("MSG_503_AlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503 Need MAIL before RCPT.
        /// </summary>
        internal static string MSG_503_NeedMailBeforeRcpt {
            get {
                return ResourceManager.GetString("MSG_503_NeedMailBeforeRcpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503 Nested MAIL command.
        /// </summary>
        internal static string MSG_503_NestedMailCommand {
            get {
                return ResourceManager.GetString("MSG_503_NestedMailCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503 HELO/EHLO Command not issued.
        /// </summary>
        internal static string MSG_503_NoHeloEhlo {
            get {
                return ResourceManager.GetString("MSG_503_NoHeloEhlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 530 Relaying not allowed for policy reasons.
        /// </summary>
        internal static string MSG_530_RelayingNotAllowed {
            get {
                return ResourceManager.GetString("MSG_530_RelayingNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 550 Max errors exceeded.
        /// </summary>
        internal static string MSG_550_MaxErrors {
            get {
                return ResourceManager.GetString("MSG_550_MaxErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 553 Invalid address {0}.
        /// </summary>
        internal static string MSG_553_InvalidAddress {
            get {
                return ResourceManager.GetString("MSG_553_InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 553 Unknown email address {0}.
        /// </summary>
        internal static string MSG_553_UnknownEmailAddress {
            get {
                return ResourceManager.GetString("MSG_553_UnknownEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 554 Misbehaved SMTP session (EarlyTalker).
        /// </summary>
        internal static string MSG_554_MisbehavedSMTPSession {
            get {
                return ResourceManager.GetString("MSG_554_MisbehavedSMTPSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client {0} connected, sess={1}, ID={2}..
        /// </summary>
        internal static string MSG_Connected {
            get {
                return ResourceManager.GetString("MSG_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client {0} disconnected, sess={1}, ID={2}..
        /// </summary>
        internal static string MSG_Disconnected {
            get {
                return ResourceManager.GetString("MSG_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTPsession::Exception: .
        /// </summary>
        internal static string MSG_Exception {
            get {
                return ResourceManager.GetString("MSG_Exception", resourceCulture);
            }
        }
    }
}
